CREATE LOGIN [EXWAP\ADFS$] FROM WINDOWS WITH DEFAULT_DATABASE=[ManualMF], DEFAULT_LANGUAGE=[us_english]
GO

CREATE TABLE [dbo].[PERMISSIONS] (
    [UPN]           NVARCHAR (64) NOT NULL,
    [VALID_UNTIL]   DATETIME      NOT NULL,
    [FROM_IP]       VARBINARY(16)   NULL,
    [REQUEST_STATE] TINYINT       NOT NULL,
    PRIMARY KEY CLUSTERED ([UPN] ASC)
);

ALTER DATABASE [ManualMF] SET ENABLE_BROKER